export interface VariantMeta {
  title: string;
  description: string;
  keywords: string;
  url: string;
  siteName: string;
  shortName: string;
  subject: string;
  classification: string;
  categories: string[];
  features: string[];
}

export const VARIANT_META: { full: VariantMeta; [k: string]: VariantMeta } = {
  full: {
    title: 'World Monitor - Real-Time Global Intelligence Dashboard',
    description: 'Real-time global intelligence dashboard with live news, markets, military tracking, infrastructure monitoring, and geopolitical data. OSINT in one view.',
    keywords: 'global intelligence, geopolitical dashboard, world news, market data, military bases, nuclear facilities, undersea cables, conflict zones, real-time monitoring, situation awareness, OSINT, flight tracking, AIS ships, earthquake monitor, protest tracker, power outages, oil prices, government spending, polymarket predictions',
    url: 'https://worldmonitor.app/',
    siteName: 'World Monitor',
    shortName: 'WorldMonitor',
    subject: 'Real-Time Global Intelligence and Situation Awareness',
    classification: 'Intelligence Dashboard, OSINT Tool, News Aggregator',
    categories: ['news', 'productivity'],
    features: [
      'Real-time news aggregation',
      'Stock market tracking',
      'Military flight monitoring',
      'Ship AIS tracking',
      'Earthquake alerts',
      'Protest tracking',
      'Power outage monitoring',
      'Oil price analytics',
      'Government spending data',
      'Prediction markets',
      'Infrastructure monitoring',
      'Geopolitical intelligence',
    ],
  },
  tech: {
    title: 'Tech Monitor - Real-Time AI & Tech Industry Dashboard',
    description: 'Real-time AI and tech industry dashboard tracking tech giants, AI labs, startup ecosystems, funding rounds, and tech events worldwide.',
    keywords: 'tech dashboard, AI industry, startup ecosystem, tech companies, AI labs, venture capital, tech events, tech conferences, cloud infrastructure, datacenters, tech layoffs, funding rounds, unicorns, FAANG, tech HQ, accelerators, Y Combinator, tech news',
    url: 'https://tech.worldmonitor.app/',
    siteName: 'Tech Monitor',
    shortName: 'TechMonitor',
    subject: 'AI, Tech Industry, and Startup Ecosystem Intelligence',
    classification: 'Tech Dashboard, AI Tracker, Startup Intelligence',
    categories: ['news', 'business'],
    features: [
      'Tech news aggregation',
      'AI lab tracking',
      'Startup ecosystem mapping',
      'Tech HQ locations',
      'Conference & event calendar',
      'Cloud infrastructure monitoring',
      'Datacenter mapping',
      'Tech layoff tracking',
      'Funding round analytics',
      'Tech stock tracking',
      'Service status monitoring',
    ],
  },
  happy: {
    title: 'Happy Monitor - Good News & Global Progress',
    description: 'Curated positive news, progress data, and uplifting stories from around the world.',
    keywords: 'good news, positive news, global progress, happy news, uplifting stories, human achievement, science breakthroughs, conservation wins',
    url: 'https://happy.worldmonitor.app/',
    siteName: 'Happy Monitor',
    shortName: 'HappyMonitor',
    subject: 'Good News, Global Progress, and Human Achievement',
    classification: 'Positive News Dashboard, Progress Tracker',
    categories: ['news', 'lifestyle'],
    features: [
      'Curated positive news',
      'Global progress tracking',
      'Live humanity counters',
      'Science breakthrough feed',
      'Conservation tracker',
      'Renewable energy dashboard',
    ],
  },
  finance: {
    title: 'Finance Monitor - Real-Time Markets & Trading Dashboard',
    description: 'Real-time finance and trading dashboard tracking global markets, stock exchanges, central banks, commodities, forex, crypto, and economic indicators worldwide.',
    keywords: 'finance dashboard, trading dashboard, stock market, forex, commodities, central banks, crypto, economic indicators, market news, financial centers, stock exchanges, bonds, derivatives, fintech, hedge funds, IPO tracker, market analysis',
    url: 'https://finance.worldmonitor.app/',
    siteName: 'Finance Monitor',
    shortName: 'FinanceMonitor',
    subject: 'Global Markets, Trading, and Financial Intelligence',
    classification: 'Finance Dashboard, Market Tracker, Trading Intelligence',
    categories: ['finance', 'news'],
    features: [
      'Real-time market data',
      'Stock exchange mapping',
      'Central bank monitoring',
      'Commodity price tracking',
      'Forex & currency news',
      'Crypto & digital assets',
      'Economic indicator alerts',
      'IPO & earnings tracking',
      'Financial center mapping',
      'Sector heatmap',
      'Market radar signals',
    ],
  },
  gtd: {
    title: 'World Monitor GTD - Global Threat & Disruption',
    description: 'GTD-focused operational view for disruption, instability, intelligence signals, and rapid situational updates.',
    keywords: 'GTD dashboard, global threats, disruption monitoring, instability, geopolitical intelligence, crisis tracking',
    url: 'https://gtd.worldmonitor.app/',
    siteName: 'World Monitor GTD',
    shortName: 'WorldMonitorGTD',
    subject: 'Global Threat and Disruption Monitoring',
    classification: 'Threat Dashboard, Intelligence Tracker',
    categories: ['news', 'security'],
    features: [
      'Threat-focused map',
      'Instability tracking',
      'Conflict intelligence',
      'Risk posture updates',
      'Rapid source aggregation',
    ],
  },
  local: {
    title: 'Local Monitor - Boston & Regional Operations',
    description: 'Boston and regional operations dashboard with local headlines, transit, weather, outages, and Boston open data overlays.',
    keywords: 'Boston dashboard, MBTA, local weather, local outages, Boston open data, city operations',
    url: 'https://local.worldmonitor.app/',
    siteName: 'Local Monitor',
    shortName: 'LocalMonitor',
    subject: 'Boston and Regional Operations Monitoring',
    classification: 'Local Operations Dashboard',
    categories: ['news', 'local'],
    features: [
      'Boston open data overlays',
      'MBTA vehicle and alert tracking',
      'Local weather and service outage monitoring',
      'Boston and metro headlines',
    ],
  },
  osint: {
    title: 'OSINT Monitor - Workbench',
    description: 'OSINT workbench for source discovery, cyber signals, outage tracking, and fast investigative triage.',
    keywords: 'OSINT, open source intelligence, investigative tools, cyber intelligence, outage monitoring',
    url: 'https://osint.worldmonitor.app/',
    siteName: 'OSINT Monitor',
    shortName: 'OSINTMonitor',
    subject: 'Open Source Intelligence Operations',
    classification: 'OSINT Workbench',
    categories: ['security', 'news'],
    features: [
      'OSINT workbench panel',
      'Source-focused feed sets',
      'Cyber and outage monitoring',
      'Rapid link generation workflows',
    ],
  },
};
